github_step_summary: false  # disable default GitHub summary

exclude_paths:
  - '**'  # exclude everything by default

include_paths:
  - '.github/workflows/superlinter.yml'
  - 'library/books.json'
  - 'API-Build/routes/subscribers.js'
