name: JS Lint Auto-Fix (Manual Approval)

on:
  workflow_dispatch:  # Manually triggered

permissions:
  contents: write

jobs:
  lint-and-fix:
    runs-on: ubuntu-latest
    environment:
      name: lint-approval

    strategy:
      matrix:
        folder: [API-Build, test_debug_js.js]  

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies in ${{ matrix.folder }}
        run: npm install
        working-directory: ${{ matrix.folder }}

      - name: Lint and auto-fix JS in ${{ matrix.folder }}
        run: npx standard --fix "./**/*.js"
        working-directory: ${{ matrix.folder }}

      - name: Commit and push changes (if any)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add ${{ matrix.folder }}
          if ! git diff --cached --quiet; then
            git commit -m "chore: auto-fix JS in ${{ matrix.folder }} via GitHub Actions"
            git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          else
            echo "No changes to commit."
