name: Greeting on variable day

on:
  workflow_dispatch

#permissions:
#  actions: none
#  checks: none
 # contents: read
 # deployments: none
 # id-token: none
 # issues: none
 # packages: none
 # pull-requests: none
 # repository-projects: none
 # security-events: none
 # statuses: none

env:
  DAY_OF_WEEK: Monday

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
    steps:
      - name: Say Hello
        run: echo "$Greeting, today is $DAY_OF_WEEK!"
